name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1
    - name: Use Nodejs 
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    - name: Install packages
      run: |
        npm ci
    # - name: Run tests
    #   run: |
    #     npm test
